### ISSUE TITLE
Apple TV skipped, because atvscript discovered UUID instead of a MAC address

### ISSUE THREAD

**Issue by robin-moser** [maxileith/homebridge-appletv-enhanced#20]
Hi, I wanted to try the awesome plugin.

Unfortunately, my Apple TV doesn't get picked up by the plugin.
Looking through debug logs and older issues, i found the problem:

```
./atvscript scan | jq
[...]
      "name": "TV",
      "address": "xx.xx.xx.xx (correct ip)",
      "identifier": "D4XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
      "device_info": {
        "model": "Gen4",
        "model_str": "Apple TV 4",
[...]
```
So the TV returns an identifier UUID instead of a MAC address and therefore is skipped in the discovery process (https://github.com/maxileith/homebridge-appletv-enhanced/commit/184162154dd7aa9ed535fb1351164776648abe77). `atvremote scan` returns four different identifiers, where only one of them is a MAC address. Could this be because I use the Apple TV as a home hub?

Is there a workaround to manually add the Apple TV? 

Thanks for your help!

**Comment by maxileith** [comment]
Hi @robin-moser ,

thanks for opening the issue. This is indeed a problem. I have added the MAC-Address filter originally to solve issue #2.

The Apple TVs are reporting, like you said, multiple identifieres. I am always using the MAC-Address as an identifier in my plugin architecture. The problem is that the `atvremote scan` command is listing all identifiers but the `atvscript scan` command only one. This seems to be the MAC-Address in most cases, which is good.

However, when the `atvscript scan` command returns another identifier, like a UUID, the plugin used to add another accessory which turns on the TV, initiates pairing and all that stuff ... which is unwanted. This is why I did the fix regarding #2.

So in order to fix that, `atvscript scan` would have to return all identifiers. Somebody probably need to do a PR over there ;)

**Comment by ahwman** [comment]
I’m having this exact same issue.  What’s puzzling to me is why it’s only happening with 1 out of my 7 Apple TV’s?

**Comment by ahwman** [comment]
Would it make a difference if we switch from hard wired to WIFI on the problem Apple TV as this would expose a different MAC address?

**Comment by maxileith** [comment]
@ahwman you can try. However, I think it is unlikely that it will change. I know people who use both in their Homes and are running the plugin with no issues.

I have the issue on my ToDo list and will resolve this as soon as possible. However, the plugin is still pretty new and there are still a few bugs and room for improvement. I will keep you updated on this issue regarding the Identifier problem.

**Comment by ahwman** [comment]
Thank you so much for the update.  I’m really enjoying this plugin and thank you for you talent and hard work! 😀

**Comment by robin-moser** [comment]
Thank you for your effort! 
I installed the plugin locally for now and disabled the check for MAC addresses, this now works fine for me, but of course is not a viable solution because of #2.

**Comment by maxileith** [comment]
@robin-moser @ahwman could you please send me the output of `/var/lib/homebridge/appletv/enhanced/.venv/bin/atvscript -s xxx.xxx.xxx.xxx scan`, where xxx.xxx.xxx.xxx is the IP of the Apple TV?

I especially am interested to know wether or not the MAC-Address is returned when using doing unicast discovery.

**Comment by ahwman** [comment]
{"result": "success", "datetime": "2023-11-09T19:21:56.049423-05:00", "devices": [{"name": "Master Bedroom Apple TV", "address": "192.168.1.117", "identifier": "E3A1DB34-2984-4976-AA4B-5FB748A94117", "device_info": {"model": "Gen4", "model_str": "Apple TV 4", "operating_system": "TvOS", "version": "17.1"}, "services": [{"protocol": "companion", "port": 49153}, {"protocol": "airplay", "port": 7000}, {"protocol": "mrp", "port": 49157}, {"protocol": "raop", "port": 7000}]}]}

**Comment by maxileith** [comment]
Okay, thanks for the reply. I did implement Unicode device discovery in #23. However, from the output that you both have sent me, this will not fix your problem. I am currently waiting for the PR that I have opened at pyaz. to be reviewed by the maintainer (PR is linked above).

**Comment by maxileith** [comment]
I just discovered that there is the `atvremote -s xxx.xxx.xxx.xxx mac` command. Can you try this an check if this command returns the MAC-Address?

**Comment by ahwman** [comment]
I think we may have a winner 😀

chuck@MacBook Pro ~ % /Users/chuck/.homebridge/appletv-enhanced/.venv/bin/atvremote -s 192.168.1.117 mac       
50:32:37:80:6C:41

**Comment by maxileith** [comment]
Thanks for replying. It would be a working but hacky solution. I have updated the PR https://github.com/postlund/pyatv/pull/2282 to include the Mac Adress on the `atvscript scan` response.

**Comment by ahwman** [comment]
Thanks for the update.  Hopefully the will incorporate this change into atvscript scan going forward…

**Comment by ahwman** [comment]
Just updated to v0.5.0 and added my static IP for the undiscovered ATV and restarted both the ATV as well as the plugin, however it is still not being discovered.  Any thoughts?

**Comment by maxileith** [comment]
@ahwman I did thought that the unicast discovery would help. However after this comment I already knew it would not help. We still need to wait for the PR to get merged.

**Comment by ahwman** [comment]
Thanks for the confirmation.  I’m still unclear as to why only 1 of my Apple TV’s isn’t reporting the MAC address…

**Comment by maxileith** [comment]
@ahwman We have circumscribed the issue sufficient to know where the problem is and how to fix it.

**Comment by ahwman** [comment]
That’s great news! Thank you so much for all of your hard work… 😀

**Comment by BrandonHacks** [comment]
I think this is related to my issue as well. No matter what I’ve tried, I cannot get my Apple TV 4K to work with this. I have another Apple TV that did get discovered(which I actually didn’t care to add.)

**Comment by maxileith** [comment]
Hi everybody,

fyi, I am still waiting for the PR to get reviewed. I haven't forgotten the bug. Seems like the owner of pyatv is on vacation since there are no commits on this repository since a month or so ...

**Comment by ahwman** [comment]
Thank you for keeping us updated… 😀

**Comment by ahwman** [comment]
Interesting update:  Today I upgraded the undetected Apple TV to tvOS 17.2, and upon the first reboot, it was discovered by the Apple TV plug-in, allowing me to pair it. I thought I was home free, however it never appeared again, so I wasn’t able to add it to HomeKit.

**Comment by maxileith** [comment]
The required changes have just been merged in `pyatv`, see https://github.com/postlund/pyatv/pull/2282. Now we have to wait until the next release of pyatv.

Additionally, changes in the dependency `@sebbo2002/node-pyatv` are required, which is used to integrate pyatv in the plugin. I have created an PR for that: https://github.com/sebbo2002/node-pyatv/pull/287

**Comment by ahwman** [comment]
Thanks so much for staying on top of this and keeping us informed. You’re a great developer and your hard work is appreciated!

**Comment by maxileith** [comment]
sebbo2002/node-pyatv#287 has been merged as well. The changes are included in v8.0.0-develop.1 of this library.

**Comment by mrmaximas** [comment]
i have same issue with latest plugin beta (and release too)
macos catalina, node.js  v20.10.0
12/18/2023, 3:42:39 PM] [Apple TV Enhanced] Restarting Process...

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] Launched child bridge with PID 65208

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] Loaded homebridge-appletv-enhanced v0.7.1-1 child bridge successfully

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] Platform: Finished initializing platform: Apple TV Enhanced

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] Platform: Executed didFinishLaunching callback

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] Python check: Starting python check.

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] Python check: plugin dir exists.

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] 

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] Python check: Python 3.9.4 is installed and supported by the plugin.

[12/18/2023, 3:42:40 PM] [Apple TV Enhanced] Python check: Virtual environment already exists.

[12/18/2023, 3:42:41 PM] [Apple TV Enhanced] Python check: Venv is using current system python version (3.9.4).

[12/18/2023, 3:42:41 PM] [Apple TV Enhanced] Python check: Checking if pip is up-to-date ...

[12/18/2023, 3:42:51 PM] [Apple TV Enhanced] Python check: Pip is up-to-date

[12/18/2023, 3:42:51 PM] [Apple TV Enhanced] Python check: Python requirements are satisfied.

[12/18/2023, 3:42:51 PM] [Apple TV Enhanced] Python check: Finished

[12/18/2023, 3:42:51 PM] [Apple TV Enhanced] Platform: Setting the storage path of the PyATV instance to /Users/ajax/.homebridge

[12/18/2023, 3:42:51 PM] [Apple TV Enhanced] CustomPyATVInstance: Set atvscript path to "/Users/ajax/.homebridge/appletv-enhanced/.venv/bin/atvscript".

[12/18/2023, 3:42:51 PM] [Apple TV Enhanced] CustomPyATVInstance: Set atvremote path to "/Users/ajax/.homebridge/appletv-enhanced/.venv/bin/atvremote".

[12/18/2023, 3:42:51 PM] [Apple TV Enhanced] Platform: Starting device discovery ...

[12/18/2023, 3:42:51 PM] [Apple TV Enhanced] Platform: Starting device discovery ...

[12/18/2023, 3:42:58 PM] [Apple TV Enhanced] Platform: finished multicast device discovery

[12/18/2023, 3:42:58 PM] [Apple TV Enhanced] Platform: Found Apple TV ATV4 Bedroom (42E1756C-8C2F-4743-ADCB-ADF5D2455AFF / 192.168.xx.xx).

[12/18/2023, 3:42:58 PM] [Apple TV Enhanced] Platform: Identifier 42E1756C-8C2F-4743-ADCB-ADF5D2455AFF is not a MAC-Address. ATV4 Bedroom (192.168.xx.xx) is therefore skipped.

[12/18/2023, 3:42:58 PM] [Apple TV Enhanced] Platform: Found Apple TV ATV4 Living Room (126A1473-CCEA-4219-8D70-68F5C290F95E / 192.168.xx.xx).

[12/18/2023, 3:42:58 PM] [Apple TV Enhanced] Platform: Identifier 126A1473-CCEA-4219-8D70-68F5C290F95E is not a MAC-Address. ATV4 Living Room (192.168.xx.xx) is therefore skipped.

[12/18/2023, 3:42:58 PM] [Apple TV Enhanced] Platform: Finished device discovery.

**Comment by maxileith** [comment]
Hello everybody,

could you guys check if your Apple TVs now work with version v1.0.0-0? 

Merry Christmas 🎄

**Comment by ahwman** [comment]
Unfortunately I’ve swapped out the undetected Apple TV for another one sitting in storage so sadly I’m of no help in this situation.  I hope this version fixes the problem for others…

Merry Christmas to you as well and thanks again for your hard work… 😀🎄

**Comment by BrandonHacks** [comment]
Merry Christmas!! I just got all my TV’s setup with the latest update. Working great now, thanks!

**Comment by wgalternate** [comment]
Working for me with the beta update as well!
